### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by geometry88** [Synestraa/Highcall-Library#10]
Why can not I declare HIGHCALL globally and call, before everything was normal, now is not obtained, differently and do not understand, please help :)
![1](https://cloud.githubusercontent.com/assets/16748478/19421021/0da05ad0-9400-11e6-913a-96de91025034.png)
![2](https://cloud.githubusercontent.com/assets/16748478/19421020/0da041ee-9400-11e6-81f2-15e2c3635c8c.png)

**Comment by Synestraa** [comment]
I apologize, I made a mistake. This will be fixed with the new update. 

Edit: It should be fine now! Thanks for pointing out the fault.

**Comment by geometry88** [comment]
Thanks you!
