### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by GameTrainersMexClan** [Synestraa/Highcall-Library#13]
Hello, I linked the library without problems but HcWriteVirtualMemory and HcProcessWriteMemory fail to change memory while WriteProcessMemory works fine with the same parameters. I am testing on windows 10 64-bit latest build. DebugPriviledge is enable. None of the parameters was left to zero. I haven't tested GetLastError() but no crash occurs. Simply it doesn't change memory. Thanks in advance.

**Comment by Synestraa** [comment]
hey. have you called HcInitialize somewhere? the syscall indices need to be acquired beforehand. :)

**Comment by GameTrainersMexClan** [comment]
my bad thanks a lot.
