### ISSUE TITLE
Some suggestions and more bugs 

### ISSUE THREAD

**Issue by GameTrainersMexClan** [Synestraa/Highcall-Library#18]
Hello, you don't need to hard code the syscall numbers, you can get them by loading libraries into memory, then looking for API functions you need to hook, then convert RVA to RAW and find out syscall numbers in disk file of every dll; I can provide you some example code although I suppose you already know this. By doing so, highcall library will no longer break after every windows update. On the other hand I would like to report several name collisions between highcall library and MFC framework libraries, thereby I have not been able to compile MFC projects, only plain win32 ones.  Maybe I'm doing something wrong but I just wanted  to let you know. Best regards.

**Comment by Synestraa** [comment]
hey, thanks.

first of:
while having the system call indices dynamically traced is a solid option, I've used it before and I see some problems. for example, to obtain the syscall indices, you can look either in your own address space, or you can use some ntdll apis to get the corresponding syscall id from the file itself, ensuring no modification. but theres 2 problems with both of these, for stealth. for the first one, you are accessing potentially modified memory, as seen in cases where antiviruses and other software uses direct assembly modification to get detours implemented on the known address, leaving the syscall index damaged and barely tracable from that point, not an option. for the second, you will leave a trace with the ntdll apis, but that's about it.

second:
supporting x64 in wow64 processes would be much harder to do. as is, all I have to do is get the latest ntdll.dll of windows 10 to ensure that I have all the newest indices, it's not as hard as It once was when I was starting with the project.

thanks a lot for your feedback, and please tell me this; in your name collision issue, could you tell me which collisions were there?

**Comment by GameTrainersMexClan** [comment]
I understand and its very logical. I would go ultimately for the files themselves, since system dll's are rarely modified by any application. Copies loaded in memory are very frequently hooked by the OS itself or other apps. But I think its a reasonable price to pay to assure that highcall will continue working even if not maintained anymore. In regard to the name collisions with mfc I can't tell because there are many. As soon as you add stdafx.h, crazy hour begins. Maybe without precompiled headers things could go along, I'm not sure but I will try and report. Best regards,
