### ISSUE TITLE
After updating Windows 7 (KB3177467) -> does not work HighCall

### ISSUE THREAD

**Issue by geometry88** [Synestraa/Highcall-Library#19]
Hello, after updating Windows 7 ([KB3177467](http://support.microsoft.com/kb/3177467)) -> does not work HighCall
before this update([KB3177467](http://support.microsoft.com/kb/3177467)) everything worked well in the release build

Windows 7 x64 Ultimate (6.1.7601)

**Comment by Synestraa** [comment]
hey.

could you debug the HcInitialize procedure in debug mode and check which procedure (likely in an .asm file) is causing the crash?

**Comment by geometry88** [comment]
[https://youtu.be/py1c11nm7bA](https://youtu.be/py1c11nm7bA)

**Comment by Synestraa** [comment]
temporary fixed applied in latest release.

please try it out and tell me if it works now.

**Comment by geometry88** [comment]
Yes, works, thanks you ^_^
