### ISSUE TITLE
Add function

### ISSUE THREAD

**Issue by geometry88** [Synestraa/Highcall-Library#21]
Hello, can you please add the [SendMessage](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644950(v=vs.85).aspx) function and the [GetAsyncKeyState](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646293(v=vs.85).aspx) function, since HcHookRecreateCode does not work well on some versions of windows

Thanks you ^^

**Comment by Synestraa** [comment]
done, I'll add some more as per request :)

please let me know if they work fine.

**Comment by geometry88** [comment]
thanks, everything works fine)

**Comment by geometry88** [comment]
Hmm, no, on x32 GetAsyncKeyState does not work

**Comment by geometry88** [comment]
HcGetAsyncKeyState on version x32 does not work, at 64 it works well
SendMessage not yet tested

**Comment by Synestraa** [comment]
native x86 or is it a wow64 process?

**Comment by geometry88** [comment]
native x86

**Comment by Synestraa** [comment]
let me know if it's fixed in the latest build

**Comment by geometry88** [comment]
![image](https://user-images.githubusercontent.com/16748478/36391156-fc494b4e-15ad-11e8-8474-ee869b4d6d0d.png)

**Comment by Synestraa** [comment]
okay, this should be fixed now.

**Comment by geometry88** [comment]
everything works fine, can you please add the function HcGetCursorPos? ^^
