### ISSUE TITLE
HcCreateThread

### ISSUE THREAD

**Issue by geometry88** [Synestraa/Highcall-Library#4]
Hello, you please show an example of usage: HcCreateThread

**Comment by Synestraa** [comment]
I'm still figuring this one out myself. This is a function unused by Windows 7-10.
The function that should be used is HcCreateThreadEx, I will add this to the repo in about 3 hours.

**Comment by geometry88** [comment]
Thank you)

**Comment by Synestraa** [comment]
You can check out the method HcProcessCreateThread, It's very simple in comparison to NtCreateThread.

**Comment by geometry88** [comment]
Thank you, I'm already using it)
