### ISSUE TITLE
NtProtectVirtualMemory return 0xC0000005

### ISSUE THREAD

**Issue by Redict** [Synestraa/Highcall-Library#5]
In native win32 application it is working fine, but in one Game it is failing with this code:/

**Comment by Synestraa** [comment]
This would happen if you tried to protect un-allocated memory, check the parameters you're passing to it.

**Comment by Redict** [comment]
```
LPVOID* addr = (LPVOID*)(GameDll + addresses[i]);
HcProtectVirtualMemory(NtCurrentProcess, addr, (PSIZE_T)sizeof(modifiers[i]), PAGE_EXECUTE_READWRITE, oldFWprotect);
```

**Comment by Synestraa** [comment]
You need to verify that you have permissions necessary to change protection of that process, and that the address you specified is in a valid region.

**Comment by Redict** [comment]
How do I have to check it? Does your library provides that thing?
VirtualProtect works fine for me:/

**Comment by Redict** [comment]
And why **OldAccessProtection** is not a link?

**Comment by Synestraa** [comment]
I'm not quite sure what exactly could be causing the problem you're having, I'm gonna try and guess.

LPVOID\* addr = (LPVOID*)(GameDll + addresses[i]);
SIZE_T Size = sizeof(modifiers[i]);
DWORD OldProtect;
HcProtectVirtualMemory(NtCurrentProcess, addr, &Size, PAGE_EXECUTE_READWRITE, &OldProtect);

Try this.

**Comment by Redict** [comment]
Same thing happening
[Image](https://i.gyazo.com/26f5cd49fd5475a430fba5a620b12b9e.png)
There's codes.

**Comment by Synestraa** [comment]
This is happening on 64bit? What OS are you using? Did you try enabling debug permissions? Is VirtualProtect from kernel32 working?

`HcProcessSetPrivilegeW(NtCurrentProcess, SE_DEBUG_NAME, TRUE)`

**Comment by Redict** [comment]
I am using Win10 x64, made a x32 DLL for x32 application. Debug Privileges already enabled:/

**Comment by Synestraa** [comment]
Yes, but if you call VirtualProtect, with the exact same code as I posted you, does it return (5) with GetLastError()?

**Comment by Redict** [comment]
It is returns 57

**Comment by Synestraa** [comment]
Error 0x57 means that you are passing the function invalid parameters, please check the first 2 parameters, something is wrong with them.

This is unrelated to the library.

**Comment by Redict** [comment]
Ok, can you provide me some example of HcProtectVirtualMemory? Small piece of code.

**Comment by Synestraa** [comment]
Check how HcProcessWriteMemory uses it.
The second parameter is important, if the location is invalid, it will return access denied.

To check if the address is valid, you will need to debug your program, breakpoint it before the call HcProtectVirtualMemory, snatch the address that its going to write to, copy it and search for it in a memory viewer (Cheat Engine, Artmoney...). 
If the memory region is invalid, or you do not have access to it, then you have the reason why It's failing.

**Comment by geometry88** [comment]
I also use HcProcessWriteMemory and I have all the normal :)

**Comment by Redict** [comment]
Can you check up my source, am I doing wrong? 
[Source](http://pastebin.com/XeGqAvWd)

**Comment by Synestraa** [comment]
The last parameter of HcProtectVirtualMemory cannot be null.
If your addresses are valid, I really recommend using HcProcessWriteMemory instead of what you're doing now.

And I still insist you read what I told you earlier.
For now I'm closing this, if you have any further issues please re-open, but confirm that the bug is not coming from you first.

**Comment by Redict** [comment]
My addresses are 100% valid.
HcProcessWriteMemory returns 0x8000000D
