### ISSUE TITLE
unresolved external symbol "_HcCreateThreadEx"

### ISSUE THREAD

**Issue by geometry88** [Synestraa/Highcall-Library#6]
Hello, I updated and now writes that:
Error LNK2001 unresolved external symbol "_HcCreateThreadEx"
Before it was all excellent
Thank you in advance.

**Comment by Synestraa** [comment]
I tested it just now in x86, and x86_64. Seems to be working fine, you just need to have a compiled .lib for the build type you're using.

**Comment by geometry88** [comment]
Thanks you.
