### ISSUE TITLE
Missing function call

### ISSUE THREAD

**Issue by C485** [Synestraa/Highcall-Library#7]
Hello,

I looked into you library and it's awsome! You got a same idea as I xD

Ok so, in HcVirtualProtectEx after calling HcProtectVirtualMemory with 0xC0000045 error code, you should realy call RtlFlushSecureMemoryCache and call HcProtectVirtualMemory again.

BTW:
I made little lib that will be very usefull in your library, it's called "ReturnAddressHider".
I can make 'pull request' ( lib will be ported to C style so it will fil into your lib ), just let me know.

**Comment by Synestraa** [comment]
I'll check out what you suggested, thanks.

Feel free to make a pull request.
