### ISSUE TITLE
HcGetCursorPos,HcSendMessageA,HcEnumWindows

### ISSUE THREAD

**Issue by geometry88** [Synestraa/Highcall-Library#9]
HcGetCursorPos\HcSendMessageA\HcEnumWindows\HcGetWindowThreadProcessId\HcPostMessageA

What happened to these functions?

**Comment by Synestraa** [comment]
The way they functioned made them redundant to be kept in files after [HcHookRecreateCode](https://github.com/Synestraa/Highcall-Library/blob/master/Highcall%20Library/highcall/src/hchook.c#L530) was added.

They can easily be created by the user as shown in an example of using OpenProcess [here.](https://github.com/Synestraa/Highcall-Library/blob/master/Example/Highcall%20Example/main.cpp#L186) The example is made with OpenProcess from kernelbase.

**Comment by geometry88** [comment]
Big thanks you ^^
